spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@estudos.p2lqx.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=Estudos
      auto-index-creation: true
  application:
    name: webflux

